### ISSUE TITLE
Realizar diagramas de secuencia

### ISSUE THREAD

**Issue by MarioDiego12** [Cuaren-team/Cuanren-team#13]
Como desarrollador 
Quiero crear diagramas de secuencia 
Para modelar la interacción entre objetos en un sistema según UML.

**Comment by fernanda555** [comment]
El primer diagrama de secuencia ya ha sido terminado y subido a la sección de arquitectura del proyecto.

**Comment by fernanda555** [comment]
Los diagramas de secuencia ya fueron diseñados, pero deben ser subidos a la parte de Arquitectura del proyecto.
