### ISSUE TITLE
Revisar los comentarios 

### ISSUE THREAD

**Issue by MarioDiego12** [Cuaren-team/Cuanren-team#17]
Como desarrollador 
Quiero revisar los comentarios
Para poder adquirir la retroalimentación correspondiente brindada por el colaborador

**Comment by fernanda555** [comment]
No debemos descuidar esta tarea, cada uno debe reporta su avance en las diferentes tareas.

**Comment by fernanda555** [comment]
Se está llevando un control exhaustivo de los comentarios para reportar todo el avance en cada una de las tareas.
