### ISSUE TITLE
Desarrollar los casos de uso

### ISSUE THREAD

**Issue by fernanda555** [Cuaren-team/Cuanren-team#3]
Como desarrollador quiero desarrollar los casos de uso 
para tener una estructura

**Comment by MarioDiego12** [comment]
![WhatsApp Image 2020-05-07 at 01 12 04 (1)](https://user-images.githubusercontent.com/25603357/81257148-8f7daf80-9000-11ea-9a31-382623e5d569.jpeg)
![WhatsApp Image 2020-05-07 at 01 12 04](https://user-images.githubusercontent.com/25603357/81257150-90164600-9000-11ea-9adb-776782bc21db.jpeg)
![WhatsApp Image 2020-05-07 at 01 12 03 (1)](https://user-images.githubusercontent.com/25603357/81257152-90164600-9000-11ea-96b8-500e79f229eb.jpeg)
![WhatsApp Image 2020-05-07 at 01 12 03](https://user-images.githubusercontent.com/25603357/81257154-90aedc80-9000-11ea-972a-e5a7e708d756.jpeg)
![WhatsApp Image 2020-05-07 at 01 12 02 (2)](https://user-images.githubusercontent.com/25603357/81257156-91477300-9000-11ea-81c8-80be0d7d63c1.jpeg)
![WhatsApp Image 2020-05-07 at 01 12 02](https://user-images.githubusercontent.com/25603357/81257161-9278a000-9000-11ea-94d5-1e9e0504c648.jpeg)
![WhatsApp Image 2020-05-07 at 01 12 01 (1)](https://user-images.githubusercontent.com/25603357/81257163-93113680-9000-11ea-9d3c-34d16004332b.jpeg)
![WhatsApp Image 2020-05-07 at 01 12 01](https://user-images.githubusercontent.com/25603357/81257164-93a9cd00-9000-11ea-999d-f7bd2d7468fe.jpeg)
